name = "HydroTools"
uuid = "294268b8-e54f-4c05-b811-3a0e544380dd"
version = "0.1.0"
authors = ["Clay Karnis"]

[deps]
GDAL = "add2ef01-049f-52c4-9ee2-e494f65e021a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
GDAL = "1.12.0"
Plots = "1.41.4"
